### ISSUE TITLE
`get_or_insert` could take an owned key instead of a borrow

### ISSUE THREAD

**Issue by MingweiSamuel** [mitsuhiko/memo-map#3]
Thank you for this excellent lib!

Currently with `get_or_insert` you have to provide a borrow of a key such as `&MyKey`, and if they key doesn't exist it is cloned via `ToOwned`. I think it would make more sense for `get_or_insert` to take an owned key, similar to `std`'s `Entry` APIs, which would avoid the clone. Or a separate API could be provided. Thoughts?

**Comment by mitsuhiko** [comment]
I think a separate API could be added. In quite a few cases the string is under normal circumstances not yet an allocation (you can only borrow at that point) so forcing a `String` to exist is not ideal.  The way this is used in minijinja for instance the lookup happens by `&str`, so forcing an owned type into the API would force an allocation in all cases.
